In [1]:
import pandas as pd

link = 'datasets/WTTJ_offers.csv'

df_wttj = pd.read_csv(link)

link = 'datasets/pole_emploi_offers.csv'

df_pole_emploi = pd.read_csv(link)

In [2]:
df_pole_emploi.head()

,intitule,description,date_publication,date_modif,contrat,competences,duree_travail,type_contrat,secteur_activite,agence,niveau_etudes,salaire,entreprise,description_entreprise,ville,code_postal
0,Data Analyst (H/F),À propos de SkillsFirst :\n\nSkillsFirst accom...,2024-01-05 15:43:43+00:00,2024-01-08 15:50:02+00:00,CDI,"[{'code': '109527', 'libelle': 'Adapter les ou...",35H Travail en journée,Temps plein,Formation continue d'adultes,NaN,NaN,"Annuel de 42000,00 Euros à 48000,00 Euros sur ...",EDUGROUPE,NaN,75 - PARIS 16,75016.0
1,Data analyst,Tu souhaites une aventure humaine et challenge...,2024-01-05 09:23:05+00:00,2024-01-08 12:50:51+00:00,CDI,"[{'code': '109527', 'libelle': 'Adapter les ou...",39H Travail en journée,Temps plein,"Ingénierie, études techniques",NaN,NaN,"Annuel de 30000,00 Euros sur 12 mois",FORTIL NORD,NaN,59 - VILLENEUVE D ASCQ,59491.0
2,Data analyst,Nous sommes une entreprise de services numériq...,2024-01-04 12:29:52+00:00,2024-01-08 16:02:26+00:00,CDI,"[{'code': '109527', 'libelle': 'Adapter les ou...",35H Travail en journée,Temps plein,Conseil en systèmes et logiciels informatiques,NaN,NaN,NaN,VIRTUAL CONSULTING,Virtual consulting est une société spécialisé ...,59 - LILLE,59000.0
3,DATA BUSINESS ANALYST (H/F),Vous êtes un(e) Data Business Analyst confirmé...,2024-01-04 10:30:01+00:00,2024-01-05 20:16:11+00:00,CDI,"[{'code': '109527', 'libelle': 'Adapter les ou...",37H30 Travail en journée,Temps plein,Programmation informatique,NaN,Bac+5 et plus ou équivalents,NaN,HARDIS GROUPE,"""Hardis Group est une ESN, une entreprise de c...",38 - GRENOBLE,38000.0
4,Data analyst F/H (H/F),"Airbus SAS, leader mondial de l'industrie aéro...",2024-01-04 09:41:23+00:00,2024-01-05 11:49:07+00:00,MIS,"[{'code': '109527', 'libelle': 'Adapter les ou...",35H Travail en journée,Temps plein,Activités des agences de travail temporaire,NaN,NaN,"Annuel de 35000,00 Euros à 40000,00 Euros sur ...",Synergie,NaN,31 - BLAGNAC,31700.0

In [3]:
df_wttj.head()

,type_contrat,niveau_etudes,intitule,date_publication,description,contract_duration_min,salary_period,salary_min,experience,date_modif,salary_max,ville,code_postal,description_entreprise,secteur_activite
0,internship,bac_5,Data Analyst - Climate Expert - Internship,2024-01-08T14:46:02Z,"At Greenly, we are on a mission to lead the wa...",4.0,NaN,NaN,LESS_THAN_6_MONTHS,2024-01-08T14:46:03Z,NaN,Paris,NaN,"Founded in 2019 by Alexis, Matthieu and Arnaud...",SocialTech / GreenTech
1,full_time,bac_5,CDI - Product data analyst - H/F,2024-01-08T14:20:22Z,Votre rôle au sein de l’équipe Au sein du serv...,NaN,NaN,NaN,LESS_THAN_6_MONTHS,2024-01-08T14:20:23Z,NaN,Boulogne-Billancourt,NaN,"TF1 Group is global player in content, present...","Media, Advertising, AdTech / MarTech"
2,full_time,NaN,Consultant Expérimenté & Manager en « Data Ana...,2024-01-08T14:04:50Z,L’opportunité En travaillant dans une équipe e...,NaN,NaN,NaN,NaN,2024-01-08T14:04:52Z,NaN,Paris,NaN,“Building a better working world” Aider les pi...,"Strategy, Audit, Transaction Services, Digital..."
3,internship,bac_5,Data engineer/analyst (stage) H/F,2024-01-08T14:35:47Z,Tu cherches à donner du sens à ton talent et à...,5.0,NaN,NaN,NaN,2024-01-08T14:35:48Z,NaN,Paris,NaN,"En 2016, Julie, Nicolas, Cédric, Lionel et Fre...","Software, SaaS / Cloud Services, Health"
4,internship,bac_5,Stage Data Analyst,2024-01-08T14:04:56Z,Ta mission si tu l’acceptes : Au sein de notre...,5.0,monthly,750.0,LESS_THAN_6_MONTHS,2024-01-08T14:04:57Z,800.0,Paris,NaN,Lulu dans ma rue réinvente la conciergerie de ...,"Collaborative Economy, Home Care Services, Cor..."

In [5]:
df_wttj.description.iloc[0]

'At Greenly, we are on a mission to lead the way in carbon reduction and sustainability. As a Climate Strategy Expert, you’ll become an integral part of our dynamic Climate Experts team, working hand in hand with our valued customers to drive positive change and shape the future of climate strategy. Your main tasks and responsibilities: At Greenly, we are on a mission to lead the way in carbon reduction and sustainability. As a Climate Strategy Intern, your primary role will involve interpreting and analyzing complex data sets related to carbon emissions. Through precise calculations and rigorous analysis, you’ll contribute insights that drive our carbon management strategies forward. Collaborating closely with our specialized team, you will play a key role in ensuring Greenly remains at the forefront of sustainable initiatives. If you possess a keen analytical mind and are passionate about sustainability, we invite you to join us on this transformative journey 🌍📊 Your main tasks and responsibilities: Data Collection & Management:  Gather, organize, clean, and validate data related to carbon emissions, sustainability initiatives, and climate trends to ensure data integrity Data Analysis:  Utilize statistical tools to identify patterns, trends, and derive insights from complex datasets related to climate change and sustainability Report Development:  Craft detailed reports and visualizations, turning intricate data findings into comprehensible and actionable insights for the team Research & Continuous Learning:  Stay abreast of the latest developments in climate science, data analysis methods, and sustainability metrics through workshops, webinars, and courses Collaboration & Communication:  Collaborate closely with the Climate Experts team, ensuring alignment on data needs and analysis goals while regularly updating on progress and challenges Tool & Software Management:  Master and suggest improvements for the data analytics software or tools used within the company to enhance the analytical process'

# tests lanchain

In [ ]:
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())

In [ ]:
from langchain.llms import 
llm = OpenAI(model_name="text-davinci-003")
llm("explain large language models in one sentence")

In [ ]:
from langchain import PromptTemplate

template = """
blabla {job_offer}
"""

prompt = PromptTemplate(
    input_variables=["job_offer"],
    template=template
)

In [ ]:
from langchain.chains import LLMChain
chain = LLMChain(llm=llm, prompt=prompt)

print(chain.run("autoencoder"))

In [ ]:
second_prompt = PromptTemplate(
    input_variables=["ml_concept"],
    template = "Turn the concept description of {ml_concept} and explain it to me like I'm five",
)
chain_two = LLMChain(llm=llm, prompt=second_prompt)

In [ ]:
from langchain.chains import SimpleSequentialChain
overall_chain = SimpleSequentialChain(chains=[chain, chain_two], verbose=True)

explanation = overall_chain.run("autoencoder")
print(explanation)

# falcon7b

In [1]:
huggingfacehub_api_token="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"

from langchain import HuggingFaceHub

repo_id = "tiiuae/falcon-7b-instruct"
llm = HuggingFaceHub(huggingfacehub_api_token=huggingfacehub_api_token,
                     repo_id=repo_id,
                     model_kwargs={"temperature":0.6, "max_new_tokens":500})

c:\Users\royde\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\utils\_deprecation.py:127: FutureWarning: '__init__' (from 'huggingface_hub.inference_api') is deprecated and will be removed from version '1.0'. `InferenceApi` client is deprecated in favor of the more feature-complete `InferenceClient`. Check out this guide to learn how to convert your script to use it: https://huggingface.co/docs/huggingface_hub/guides/inference#legacy-inferenceapi-client.
  warnings.warn(warning_message, FutureWarning)

In [2]:
from langchain import PromptTemplate, LLMChain

template = """
Tu es un spécialiste en recrutement et offre d'emplois.
Tu vas aider l'utilisateur a ressortir les informations demandées dans une offre d'emploi fournie.

Tu vas fournir tes réponses sous formes de liste suivant cet exemple :
"Compétences techniques :
-Power BI
-Tableau
-etc...
"

Voici la demande :
{question}
"""
prompt = PromptTemplate(template=template, input_variables=["question"])
llm_chain = LLMChain(prompt=prompt, llm=llm)

In [3]:
question = """
Quelles sont les soft skill dans cette offre :

"Votre rôle au sein de l’équipe Au sein du service « Pilotage de la performance et de la recommandation »
(MYTF1, TFOU, TF1 Info, Max), qui reunit des business analyst, des data analysts, et des chargés de datavisualisation,
vous serez en charge de l'analyse, de l'évaluation et de la modélisation de la recommandation sur les offres digitales de TF1.
Vos missions seront : D'analyser les comportements des utilisateurs sur les plateformes digitales de TF1,
et de définir les opportunités de recommandation (fonctionnalités, contenus, expériences) ;
D'évaluer les recommandations proposées sur TF1 et les optimiser (algorithmes, stock, conversion) ;
De définir la méthodologie de recommandation adaptée (user, content, cohort, personnalisation…) ;
De proposer de nouvelles manières de segmenter nos audiences pour optimiser les recommandations, et définissez les spec pour les data ingénieurs ;
D'être force de proposition quant à la recommandation, à travers une veille permanente des acteurs streaming et vidéo, et de la compréhension des comportements des internautes ;
De participer à l'amélioration des méthodologies adoptées et des métadonnées utilisées ;
D’être un interlocuteur privilégié entre le service data/tech et les équipes métier eTF1 (éditorial, produit…)."

"""

print(llm_chain.run(question))

The soft skill in the given offer are:

- Soft Skills:
- Business Analysis
- Data Analysis
- Data Visualization
- Machine Learning
- Data Science
- Data Engineering
- Data Architecture
- Data Mining
- Data Warehousing
- Data Quality
- Data Management
- Data Governance
- Data Visualization
- Tableau
- Power BI
- Python
- R
- MS SQL
- Data Analysis Tools
- Business Intelligence Tools
- Data Engineering Tools
- Data Integration Tools
- Data Visualization Tools
- Data Quality Tools
- Data Governance Tools
- Data Architecture Tools
- Data Visualization Tools
- Business Intelligence Tools
- Data Analysis Tools
- Data Engineering Tools
- Business Analysis
- Data Visualization
- Machine Learning
- Data Science
- Data Science Tools
- Data Services
- Data Engineering
- Data Architecture
- Data Warehouse
- Data Mining
- Data Lake
- Data Integration
- Data Governance
- Data Visualization
- Data Visualization Tools
- Data Analysis Tools
- Business Intelligence Tools
- Data Analysis Tools
- Data Visualization Tools
- Data Analysis
- Data Analysis Tools
- Data Analysis
- Business Analysis
- Data Visualization
- Data Analysis Tools
- Data Visualization Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analyst
- Data Analysis
- Data Visualization
- Data Analysis Tools
- Business Analysis
- Data Visualization Tools
- Data Analysis Tools
- Data Visualization Tools
- Data Visualization Tools
- Data Analysis Tools
- Data Analysis
- Data Analysis Tools
- Data Visualization Tools
- Data Visualization Tools
- Data Analysis Tools
- Data Visualization Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Visualization Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis
- Data Analysis
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools
- Data Analysis Tools